"""Op log, relay, and the cross-implementation agreement check.

The last test class is the important one. Two implementations of the same merge semantics —
TypeScript on the client, Python on the server — will drift, and when they drift the API and
the UI disagree about a customer's pipeline. So the agreement is asserted against fixtures
generated by the real TypeScript replica rather than assumed.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from rainmaker.crm.materialise import materialise, pipeline_summary
from rainmaker.sync.hub import MAX_QUEUE, SyncHub
from rainmaker.sync.oplog import OpLog

FIXTURES = Path(__file__).parent / "fixtures"


def op(
    op_id: str,
    actor: str,
    entity: str,
    op_type: str = "set",
    wall: int = 1000,
    counter: int = 0,
    **extra,
) -> dict:
    return {
        "id": op_id,
        "ts": {"wall": wall, "counter": counter, "actor": actor},
        "actor": actor,
        "kind": "deal",
        "entityId": entity,
        "type": op_type,
        **extra,
    }


# ───────────────────────────────────────────────────────────── op log
class TestOpLog:
    @pytest.fixture
    def oplog(self) -> OpLog:
        return OpLog(":memory:")

    def test_append_assigns_monotonic_sequence_numbers(self, oplog: OpLog):
        stored = oplog.append(
            "ws",
            [
                op("a", "alice", "d1", field="stage", value="new"),
                op("b", "alice", "d1", field="stage", value="won"),
            ],
        )
        assert [s.seq for s in stored] == [1, 2]
        assert oplog.head("ws") == 2

    def test_duplicate_ops_are_stored_once_and_not_returned_twice(self, oplog: OpLog):
        """A client on a flaky link retries. Storing duplicates grows the log without bound
        and re-broadcasting them turns one client's retry into everyone's traffic."""
        first = oplog.append("ws", [op("a", "alice", "d1", field="x", value=1)])
        second = oplog.append("ws", [op("a", "alice", "d1", field="x", value=1)])
        assert len(first) == 1
        assert second == []
        assert oplog.stats("ws")["ops"] == 1

    def test_a_batch_containing_both_new_and_duplicate_ops_stores_only_the_new(
        self, oplog: OpLog
    ):
        oplog.append("ws", [op("a", "alice", "d1", field="x", value=1)])
        stored = oplog.append(
            "ws",
            [
                op("a", "alice", "d1", field="x", value=1),   # dup
                op("b", "alice", "d1", field="y", value=2),   # new
            ],
        )
        assert [s.op_id for s in stored] == ["b"]

    def test_workspaces_are_isolated(self, oplog: OpLog):
        oplog.append("ws1", [op("a", "alice", "d1", field="x", value=1)])
        oplog.append("ws2", [op("b", "bob", "d2", field="x", value=2)])
        assert len(oplog.since("ws1", 0)) == 1
        assert len(oplog.since("ws2", 0)) == 1
        assert oplog.since("ws1", 0)[0].op_id == "a"

    def test_the_same_op_id_may_exist_in_two_workspaces(self, oplog: OpLog):
        """Dedup is scoped to a workspace; op ids are only unique per replica, so two
        tenants can legitimately mint the same id."""
        assert len(oplog.append("ws1", [op("a", "alice", "d1", field="x", value=1)])) == 1
        assert len(oplog.append("ws2", [op("a", "alice", "d1", field="x", value=1)])) == 1

    def test_since_resumes_from_a_checkpoint(self, oplog: OpLog):
        oplog.append("ws", [op(f"op{i}", "alice", "d1", field="x", value=i) for i in range(10)])
        rest = oplog.since("ws", 4)
        assert [s.seq for s in rest] == [5, 6, 7, 8, 9, 10]

    def test_wire_form_carries_the_sequence_for_checkpointing(self, oplog: OpLog):
        stored = oplog.append("ws", [op("a", "alice", "d1", field="x", value=1)])
        assert stored[0].to_wire()["_seq"] == 1

    def test_a_malformed_op_is_rejected_with_a_useful_message(self, oplog: OpLog):
        with pytest.raises(ValueError, match="missing"):
            oplog.append("ws", [{"id": "a", "actor": "alice"}])

    def test_entity_scoped_replay(self, oplog: OpLog):
        oplog.append(
            "ws",
            [
                op("a", "alice", "d1", field="x", value=1),
                op("b", "alice", "d2", field="x", value=2),
                op("c", "alice", "d1", field="y", value=3),
            ],
        )
        assert [s.op_id for s in oplog.for_entity("ws", "deal", "d1")] == ["a", "c"]

    def test_survives_a_restart(self, tmp_path: Path):
        path = tmp_path / "log.sqlite3"
        first = OpLog(path)
        first.append("ws", [op("a", "alice", "d1", field="stage", value="won")])
        first.close()

        reopened = OpLog(path)
        assert reopened.head("ws") == 1
        assert reopened.since("ws", 0)[0].payload["value"] == "won"
        reopened.close()


# ───────────────────────────────────────────────────────────── hub
class TestSyncHub:
    @pytest.fixture
    def hub(self) -> SyncHub:
        return SyncHub(OpLog(":memory:"))

    async def test_publish_fans_out_to_subscribers(self, hub: SyncHub):
        sub = await hub.subscribe("ws", "bob", "sub-1")
        await hub.publish("ws", [op("a", "alice", "d1", field="stage", value="won")])
        message = sub.queue.get_nowait()
        assert message["type"] == "ops"
        assert message["ops"][0]["id"] == "a"

    async def test_the_origin_connection_does_not_receive_its_own_ops(self, hub: SyncHub):
        """It applied them locally before sending. Echoing wastes the exact connection most
        likely to be constrained."""
        sender = await hub.subscribe("ws", "alice", "sender")
        other = await hub.subscribe("ws", "bob", "other")
        await hub.publish("ws", [op("a", "alice", "d1", field="x", value=1)], origin="sender")
        assert sender.queue.empty()
        assert not other.queue.empty()

    async def test_duplicates_are_not_rebroadcast(self, hub: SyncHub):
        sub = await hub.subscribe("ws", "bob", "sub-1")
        payload = [op("a", "alice", "d1", field="x", value=1)]
        await hub.publish("ws", payload)
        sub.queue.get_nowait()
        await hub.publish("ws", payload)
        assert sub.queue.empty()

    async def test_ops_are_durable_before_they_are_broadcast(self, hub: SyncHub):
        """Broadcasting first would let a client observe an op a crash then loses."""
        await hub.subscribe("ws", "bob", "sub-1")
        await hub.publish("ws", [op("a", "alice", "d1", field="x", value=1)])
        assert hub.oplog.head("ws") == 1

    async def test_a_slow_subscriber_is_dropped_rather_than_buffered_forever(
        self, hub: SyncHub
    ):
        """One phone on a bad connection must not be able to exhaust server memory."""
        slow = await hub.subscribe("ws", "slow", "slow-1")
        for i in range(MAX_QUEUE + 20):
            await hub.publish("ws", [op(f"op{i}", "alice", "d1", field="x", value=i)])
        assert hub.live_count("ws") == 0
        assert slow.overflowed

    async def test_catch_up_returns_what_was_missed(self, hub: SyncHub):
        await hub.publish(
            "ws", [op(f"op{i}", "alice", "d1", field="x", value=i) for i in range(5)]
        )
        result = await hub.catch_up("ws", since=2)
        assert [o["_seq"] for o in result["ops"]] == [3, 4, 5]
        assert result["head"] == 5
        assert result["more"] is False

    async def test_presence_lists_distinct_actors(self, hub: SyncHub):
        await hub.subscribe("ws", "alice", "s1")
        await hub.subscribe("ws", "alice", "s2")   # two devices, one person
        await hub.subscribe("ws", "bob", "s3")
        assert hub.presence("ws") == ["alice", "bob"]
        assert hub.live_count("ws") == 3


# ───────────────────────────────────────────────────────────── materialisation
class TestMaterialise:
    def test_last_writer_wins_by_hlc_not_arrival_order(self):
        ops = [
            op("b", "alice", "d1", field="stage", value="won", wall=2000),
            op("a", "alice", "d1", field="stage", value="new", wall=1000),
        ]
        assert materialise(ops)[0]["stage"] == "won"

    def test_concurrent_writes_resolve_by_actor_tiebreak(self):
        ops = [
            op("x", "alice", "d1", field="stage", value="A", wall=1000, counter=0),
            op("y", "bob", "d1", field="stage", value="B", wall=1000, counter=0),
        ]
        # bob > alice, so bob wins -- and must win identically in the TypeScript replica.
        assert materialise(ops)[0]["stage"] == "B"
        assert materialise(list(reversed(ops)))[0]["stage"] == "B"

    def test_or_set_keeps_a_concurrent_add_the_remove_never_saw(self):
        ops = [
            op("1", "alice", "d1", "addTag", tag="vip", instance="alice:1"),
            op("2", "bob", "d1", "removeTag", tag="vip", instances=["alice:1"]),
            op("3", "alice", "d1", "addTag", tag="vip", instance="alice:9"),
        ]
        assert materialise(ops)[0]["tags"] == ["vip"]

    def test_a_tag_removal_arriving_first_still_cancels(self):
        ops = [
            op("2", "bob", "d1", "removeTag", tag="vip", instances=["alice:1"]),
            op("1", "alice", "d1", "addTag", tag="vip", instance="alice:1"),
        ]
        assert materialise(ops)[0]["tags"] == []

    def test_note_length_counts_undeleted_characters(self):
        ops = [
            op("1", "a", "d1", "insertText", field="notes", charId="c1", char="h", after=None),
            op("2", "a", "d1", "insertText", field="notes", charId="c2", char="i", after="c1"),
            op("3", "a", "d1", "deleteText", field="notes", charId="c1"),
        ]
        assert materialise(ops)[0]["note_lengths"]["notes"] == 1

    def test_duplicates_are_ignored(self):
        one = op("a", "alice", "d1", field="amount", value=100)
        assert materialise([one, one, one])[0]["amount"] == 100

    def test_pipeline_summary_counts_stageless_deals_rather_than_dropping_them(self):
        """A total that disagrees with what the rep can see on the board is worse than none."""
        summary = pipeline_summary(
            [
                {"id": "a", "stage": "won", "amount": 100},
                {"id": "b", "amount": 50},          # no stage
            ]
        )
        assert summary["total_count"] == 2
        assert summary["total_value"] == 150.0
        assert "unassigned" in summary["by_stage"]

    def test_pipeline_summary_tolerates_a_non_numeric_amount(self):
        summary = pipeline_summary([{"id": "a", "stage": "won", "amount": "not a number"}])
        assert summary["total_count"] == 1
        assert summary["total_value"] == 0.0


# ───────────────────────────────────────────────────────────── cross-implementation
@pytest.mark.skipif(
    not (FIXTURES / "crdt_agreement.json").exists(),
    reason="run `npm run fixtures -w @rainmaker/crdt` to regenerate",
)
class TestAgreesWithTypeScriptReplica:
    """The Python reducer and the TypeScript CRDT must agree on the same op log.

    The fixture is GENERATED BY THE REAL REPLICA (packages/crdt/scripts/fixtures.ts), not
    hand-written, so it cannot encode a shared misunderstanding. If either implementation's
    merge rule changes, this fails.
    """

    def test_field_values_agree(self):
        fixture = json.loads((FIXTURES / "crdt_agreement.json").read_text(encoding="utf-8"))
        for case in fixture["cases"]:
            got = {d["id"]: d for d in materialise(case["ops"])}
            for entity_id, expected in case["expected"].items():
                assert entity_id in got, f"{case['name']}: missing entity {entity_id}"
                for field, value in expected["fields"].items():
                    assert got[entity_id].get(field) == value, (
                        f"{case['name']}: field {field} on {entity_id} — "
                        f"python={got[entity_id].get(field)!r} ts={value!r}"
                    )

    def test_tag_sets_agree(self):
        fixture = json.loads((FIXTURES / "crdt_agreement.json").read_text(encoding="utf-8"))
        for case in fixture["cases"]:
            got = {d["id"]: d for d in materialise(case["ops"])}
            for entity_id, expected in case["expected"].items():
                assert got[entity_id]["tags"] == expected["tags"], (
                    f"{case['name']}: tags on {entity_id} disagree"
                )
